name: Run Scraper Daily

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd scraper
          npm install

      - name: Run scraper
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        run: |
          cd scraper
          node scraper.js
