name: Run Scraper Daily

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          cd scraper
          npm install

      - name: Run scraper
        run: |
          cd scraper
          node scraper.js

  geocode:
    needs: run-scraper
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      LOCATIONIQ_KEY: ${{ secrets.LOCATIONIQ_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          cd scraper
          npm install

      - name: Run geocoder
        run: |
          cd scraper
          node geocode.js
